steps:
  # Build the Docker image using the Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/auton-dh/cloud-run-source-deploy/d-pay-web-app/d-pay-web-app:$COMMIT_SHA'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/auton-dh/cloud-run-source-deploy/d-pay-web-app/d-pay-web-app:latest'
      - '.'

  # Push both tags
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'asia-southeast1-docker.pkg.dev/auton-dh/cloud-run-source-deploy/d-pay-web-app/d-pay-web-app'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'd-pay-web-app'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/auton-dh/cloud-run-source-deploy/d-pay-web-app/d-pay-web-app:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - 'asia-southeast1-docker.pkg.dev/auton-dh/cloud-run-source-deploy/d-pay-web-app/d-pay-web-app:$COMMIT_SHA'
  - 'asia-southeast1-docker.pkg.dev/auton-dh/cloud-run-source-deploy/d-pay-web-app/d-pay-web-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
